# springboot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-java-app
  template:
    metadata:
      labels:
        app: sample-java-app
    spec:
      containers:
      - name: java-app
        image: sivashankarrajendran/java-main-springboot_app:latest
        ports:
        - containerPort: 1001
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/books?serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
