# springboot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-java-service
spec:
  type: NodePort
  selector:
    app: sample-java-app
  ports:
    - port: 1001
      targetPort: 1001
      nodePort: 30008  